"""Shared constants for the distributed video processing prototype."""

CONTROL_PORT = 5000
FIXED_PORT = CONTROL_PORT

DEVICES_JSON_FILE = "devices.json"
DEVICE_ID_PREFIX = "node"

CONFIG_KEY_SPLIT_COMMAND = "split_command"
CONFIG_KEY_EXECUTE_COMMAND = "execute_command"
CONFIG_KEY_MERGE_COMMAND = "merge_command"
CONFIG_KEY_MAX_NODES = "max_nodes"

CONFIG_KEYS = (
    CONFIG_KEY_SPLIT_COMMAND,
    CONFIG_KEY_EXECUTE_COMMAND,
    CONFIG_KEY_MERGE_COMMAND,
    CONFIG_KEY_MAX_NODES,
)

PROGRESS_SPLITTING_FILE = "splitting file"
PROGRESS_SENDING_FILE = "sending file"
PROGRESS_EXECUTING = "executing"
PROGRESS_RECEIVING_FILES = "receiving files"
PROGRESS_FINISHED = "finished"
PROGRESS_MERGING_FILES = "merging files"

MESSAGE_TYPE_READY = "ready"
MESSAGE_TYPE_FILE_RECEIVED = "file_received"
MESSAGE_TYPE_FINISHED = "finished"
MESSAGE_TYPE_FAILED = "failed"

PART_FILENAME_PREFIX = "part"
PART_FILENAME_SUFFIX = ".mkv"

# Role-specific working directories under the project root.
MASTER_DIRECTORY = "master"
WORKER_DIRECTORY = "worker"

MASTER_INPUT_DIRECTORY = f"{MASTER_DIRECTORY}/input"
MASTER_OUTPUT_DIRECTORY = f"{MASTER_DIRECTORY}/output"
WORKER_INPUT_DIRECTORY = f"{WORKER_DIRECTORY}/input"
WORKER_OUTPUT_DIRECTORY = f"{WORKER_DIRECTORY}/output"
